More build tests specified

diff --git a/sbin/tests b/sbin/tests
--- a/sbin/tests
+++ b/sbin/tests
@@ -4,7 +4,23 @@ echo "--------------------------"
 echo "Checking code style rules."
 echo "--------------------------"
 if ! ./gradlew checkstyleMain checkstyleTest; then
-  echo "Style check failed"
+  echo "Style check failed."
+  exit 1
+fi
+
+echo "------------------------------"
+echo "Inspecting code with findbugs."
+echo "------------------------------"
+if ! ./gradlew findbugsMain findbugsTest; then
+  echo "Findbugs found bugs."
+  exit 1
+fi
+
+echo "------------------------"
+echo "Checking code coverage."
+echo "------------------------"
+if ! ./gradlew coberturaCheck; then
+  echo "Code coverage is insufficent."
   exit 1
 fi
 
@@ -12,6 +28,6 @@ echo "-------------------"
 echo "Running unit tests."
 echo "-------------------"
 if ! ./gradlew test; then
-  echo "Unit tests failed"
+  echo "Unit tests failed."
   exit 1
 fi
